version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  server:
    restart: always
    image: samuelvarejames/fraugsterserver:latest
    deploy:
      replicas: 20
      resources:
        limits:
          cpus: "2"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - webnet
  db:
    restart: always
    image: postgres
    networks:
      - webnet
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - cadvisor
    networks:
      - webnet
  cadvisor:
    image: google/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - webnet
  grafana:
    image: grafana/grafana:3.0.0-beta7
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
        - prometheus
    ports:
        - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - webnet

networks:
  webnet:
